ToDo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core"))
]

core/urls.py
from django.urls import path

from core.views import (
    TaskListView,
    index,
    TagListView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    task_toggle_completion
)

urlpatterns = [
    path("", index, name="index"),

    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/create", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/update", TagUpdateView.as_view(), name="tag_update"),
    path("tags/<int:pk>/delete", TagDeleteView.as_view(), name="tag_delete"),

    path("task_list/", TaskListView.as_view(), name="task_list"),
    path("task_list/create", TaskCreateView.as_view(), name="task_create"),
    path("task_list/<int:pk>/update", TaskUpdateView.as_view(), name="task_update"),
    path("task_list/<int:pk>/delete", TaskDeleteView.as_view(), name="task_delete"),

    path("task_toggle_completion/<int:pk>/", task_toggle_completion, name="task_toggle_completion")
]

app_name = "core"

core/models.py
from django.db import models
from django.utils.datetime_safe import datetime


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=511)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self) -> str:
        return self.content

    def is_end_date(self):
        return datetime.now() > self.deadline

core/forms.py
from django import forms

from core.models import Tag, Task


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ("name",)


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

        deadline = forms.DateTimeField(
            required=False
        )

        widgets = {
            "deadline": forms.widgets.DateTimeInput(attrs={"type": "datetime-local"})
        }

core/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from core.models import Task, Tag
from core.forms import TagForm, TaskForm


def index(request: HttpRequest) -> HttpResponse:
    return HttpResponseRedirect(reverse("core:task_list"))


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags").order_by("is_done")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("core:tag_list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("core:tag_list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("core:tag_list")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("core:task_list")

    def form_valid(self, form):
        form.deadline = ""
        return super().form_valid(form)


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("core:task_list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("core:task_list")


def task_toggle_completion(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, id=pk)
    if task:
        task.is_done = not task.is_done
        task.save()
    return HttpResponseRedirect(reverse("core:task_list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ToDo list</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class=" row main_container m-3">
  <div class="col-2">
  {% include "includes/sidebar.html" %}
  </div>
    <div class="col-10 container my-3 custom-card">
    {% block content %}
    {% endblock content %}
  </div>
</div>

</body>
</html>

templates/core/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <p><strong>Tag name:</strong> {{ tag.name }} </p>
  <form action="" method="post">
    {% csrf_token %}
            <input type="submit" value="Submit" class="btn btn-danger btn-outline rounded-pill">
        <a href="{% url 'core:tag_list' %}" class="btn btn-dark btn-outline rounded-pill">Back</a>
  </form>
{% endblock %}

templates/core/tag_form.html
{% extends "base.html" %}
{% block content %}
  {% load crispy_forms_filters %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" class="form-inline" novalidate>
    {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary btn-outline rounded-pill">
        <a href="{% url 'core:tag_list' %}" class="btn btn-dark btn-outline rounded-pill">Back</a>
  </form>
{% endblock %}

templates/core/tag_list.html
{% extends "base.html" %}
{% block content %}

  <h1>Tags
    <a href="{% url 'core:tag_create' %}" class="btn btn-primary btn-outline rounded-pill">
      Create
    </a>
  </h1>


  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            <span style="font-size: 20px">{{ tag.name }}</span>
          </td>
          <td>
            <a class="btn btn-info btn-outline rounded-pill"
               href="{% url 'core:tag_update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a class="btn btn-danger btn-outline rounded-pill"
               href="{% url 'core:tag_delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tags to display.</p>
  {% endif %}

{% endblock %}

templates/core/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <p><strong>Task: </strong> {{ task.content }} </p>
  <form action="" method="post">
    {% csrf_token %}
            <input type="submit" value="Submit" class="btn btn-danger btn-outline rounded-pill">
        <a href="{% url 'core:tag_list' %}" class="btn btn-dark btn-outline rounded-pill">Back</a>
  </form>
{% endblock %}

templates/core/task_form.html
{% extends "base.html" %}
{% block content %}
  {% load crispy_forms_filters %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" class="form-inline" novalidate>
    {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary btn-outline rounded-pill">
        <a href="{% url 'core:task_list' %}" class="btn btn-dark btn-outline rounded-pill">Back</a>
  </form>
{% endblock %}

templates/core/task_list.html
{% extends "base.html" %}
{% block content %}

  <h1>Tasks:
    <a href="{% url 'core:task_create' %}" class="btn btn-primary btn-outline rounded-pill">
      Create
    </a>
  </h1>


  {% if task_list %}
    {% for task in task_list %}
      <hr>
      <div class="d-flex d-row justify-content-between">


        <div><span style="font-size: 20px">{{ task.content }}</span>
          {% if task.is_done %}
            <strong>
            <span class="text-success h3 m-5">Done</span>
          {% else %}
            <span class="text-danger h3 m-5">Not done</span>
          {% endif %}
          </strong>
        </div>
        {% if task.is_done %}
          <a class="btn btn-secondary rounded-pill"
             href="{% url 'core:task_toggle_completion' task.id %}">Undo</a>

        {% else %}
          <a class="btn btn-success rounded-pill"
             href="{% url 'core:task_toggle_completion' task.id %}">Complete</a>
        {% endif %}
      </div>


      <p class="text-muted bp3-text-small m-4"> Created at: {{ task.created_at }}
        {% if task.deadline %}
          <span style="color: brown; font-weight: bold">Deadline: {{ task.deadline }}</span>
        {% endif %}

      </p>

      <p>
        Tags:
        {% for tag in task.tags.all %}
          <span class="tag">{{ tag.name }}</span>
        {% endfor %}
        <a href="{% url 'core:task_update' task.id %}" class="btn btn-sm btn-info btn-outline mx-2">Update</a>
        <a href="{% url 'core:task_delete' task.id %}" class="btn btn-sm btn-danger btn-outline mx-2">Delete</a>
      </p>

    {% endfor %}
    <hr>
  {% else %}
    <p>There are no tasks to display.</p>
  {% endif %}

{% endblock %}

templates/includes/sidebar.html
<div class="main_container">
  <div class="container my-3 custom-card">
    <h1>Menu</h1>
    <ul class="list-group">
      <li class="list-group-item">
        <a href="{% url 'core:task_list' %}">Home</a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'core:tag_list' %}">Tags</a>
      </li>
    </ul>
  </div>
</div>